name = "Phylo"
uuid = "aea672f4-3940-5932-aa44-993d1c3ff149"
author = ["Richard Reeve <Richard.Reeve@glasgow.ac.uk>"]
version = "0.4.19"

[deps]
AxisArrays = "39de3d68-74b9-583c-8d2d-e117c070f3a9"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
Missings = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
SimpleTraits = "699a6c99-e7fa-54fc-8d76-47d257e15c1d"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Tokenize = "0796e94c-ce3b-5d07-9a54-7f471281c624"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
AxisArrays = "0.4"
DataFrames = "0.21, 0.22, 1.0"
DataStructures = "0.17, 0.18"
Distributions = "0.24"
IterableTables = "^1"
LightGraphs = "^1"
Missings = "0.4, 1.0"
RecipesBase = "0.7, 0.8, ^1"
Requires = "^1"
SimpleTraits = "0.9"
Tokenize = "0.5"
Unitful = "^1"
julia = "^1"
